# CONSTANTS


DEFAULT_PORT = 80
DEFAULT_PORT_RANGE_MIN = 1024
DEFAULT_PORT_RANGE_MAX = 65535
DEFAULT_IP_ADDRESS = '127.0.0.1'
MAX_CONNECTIONS = 6
MAX_PACKAGE_LENGTH = 1024
ENCODING = 'utf-8'

# JIM
ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'
PRESENCE = 'presence'
RESPONSE = 'response'
RESPONSE_200 = "200"
RESPONSE_400 = "400"
ERROR = 'error'
